name: Build and Deploy
on:
  # run when the master branch is updated
  push:
    branches:
      - master

  repository_dispatch:
    types:
      - push-tag

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install
        run: npm install @qooxdoo/framework --no-save

      - name: Build
        run:  npx qx deploy --out=./html  --clean --source-maps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html